/*
 * This source file was generated by the Gradle 'init' task
 */
package org.roguedungeon;

import org.junit.Test;
import static org.junit.Assert.*;

public class RogueDungeonTest {
    @Test public void gameHasVersion() {
        RogueDungeon classUnderTest = new RogueDungeon();
        assertEquals("Version is not correct", "1.0.SNAPSHOT", classUnderTest.getVersion());
    }
}
