/*
 * This source file was generated by the Gradle 'init' task
 */
package org.roguedungeon;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class RogueDungeonTest {
    @Test
    public void gameHasVersion() {
        assertEquals("Version is not correct", "1.0.SNAPSHOT", RogueDungeon.getVersion());
    }
}
