name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/libs/RougeDungeon.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
